### ISSUE TITLE
Verify SDK API call for initiating face id authentication

### ISSUE THREAD

**Issue by agarwalpranab** [ibm-security-verify/verify-sdk-ios#12]
Problem Description:
Customer is trying to invoke authentication.  What is the API in Verify SDK to call so that they can trigger the fingerprint authentication using the registered authenticator?

Could you share details about how to invoke the fingerprint authentication, e.g., on iPhone using face id?

At high level, we need to:
1. Refresh for new access token
2. Create an MMFA transaction in pending status
3. Get server challenge from ISAM
4. Sign challenge with locally stored private key, and post back to ISAM along with the access token to authenticate.

More clarification from customer:
We don't intend to use push notification and QR code in the flow.  So purely looking for authenticate with registered fingerprint method directly from mobile app against ISVA.  And we are integrating with on-premise ISVA 10.0.3.  In particular, I am looking at how to use SDK call to initiate the process by calling authentication policy on ISVA - urn:ibm:security:authentication:asf:mmfa_fingerprint

Also, does Verify SDK support face id with on-premise ISAM?  On ISAM I only see user_presence and fingerprint authentication methods, there's no face id method.

**Comment by craigaps** [comment]
@agarwalpranab the `accessToken` provided in the MFA component is scoped to use only the MFA endpoints.  Therefore you can't use the authenticator `accessToken` for any other purpose i.e for authentication to other ISVA protected services.

The Verify SDK fingerprint authentication method is a generic term to represent (on iOS), Face ID or Touch ID.

Also, creating a MFA transaction to be acknowledge by a mobile app (using the SDK) is triggered by custom business logic or ISVA policy, like attempting to sign-in from a browser in-private mode.
