### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by simonwalker-celadin** [ibm-security-verify/verify-sdk-ios#7]
Are there any (or will there be) any guidelines for integrating this with React Native

**Comment by craigaps** [comment]
@simonwalker-celadin currently we have no plans to create a React Native module.  However, you can refer to this article for guidance.

https://reactnative.dev/docs/native-modules-ios.html

**Comment by craigaps** [comment]
@simonwalker-celadin currently we have no plans to create a React Native module.  However, you can refer to this article for guidance.

https://reactnative.dev/docs/native-modules-ios.html
