### ISSUE TITLE
Create authenticators initiate function 

### ISSUE THREAD

**Issue by sam-paisley** [ibm-security-verify/verify-sdk-ios#8]
@craigaps  Update SDK to create authenticators initiate function and return as JSON. 

https://docs.verify.ibm.com/verify/reference/initiateauthenticator

**Comment by craigaps** [comment]
@sam-paisley this is already support in the REST service.  Change the `Accept` header to return JSON instead of a PNG of the QR-code.  Here's an example:

```
curl --location 'https://my_isv_host/v1.0/authenticators/initiation' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer my_bearer_token' \
--data '{
	"owner": "user_UID",
	"clientId": "my_client_ID",
	"accountName": "Friendly Name"
}'
```

The SDK takes the JSON which can be obtained by parsing the QR code content or directly like the example above.
